Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2020-09, with the labels that each got.

#93 Fix some possible typos and inaccuracies in 1.1.1
  1-js/01-getting-started/1-intro/article.md
Labels: changes requested

#95 Fix some possible typos and inaccuracies in 1.1.2
  1-js/01-getting-started/2-manuals-specifications/article.md
Labels: review needed

#96 Fix possible typos, inaccuracies, omissions in 1.1.3
  1-js/01-getting-started/3-code-editors/article.md
Labels: needs +1

#97 Update translation of part 1 intro
  1-js/index.md
Labels: needs +1

#98 Fix possible typos, inaccuracies, omissions in 1.1.4
  1-js/01-getting-started/4-devtools/article.md
Labels: needs +1

#99 Fix possible typos, inaccuracies, omissions in 1.2.1
  1-js/02-first-steps/01-hello-world/1-hello-alert/index.html
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md
  1-js/02-first-steps/01-hello-world/article.md
Labels: needs +1

#101 Fix possible typos, inaccuracies, omissions in 1.2.2
  1-js/02-first-steps/02-structure/article.md
Labels: needs +1

#102 Fix possible typos, inaccuracies, omissions in 1.2.3
  1-js/02-first-steps/03-strict-mode/article.md
Labels: needs +1

#103 Fix possible typos, inaccuracies, omissions in 1.2.4
  1-js/02-first-steps/04-variables/1-hello-variables/solution.md
  1-js/02-first-steps/04-variables/2-declare-variables/solution.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
  1-js/02-first-steps/04-variables/article.md
Labels: needs +1

#104 Fix possible typos, inaccuracies, omissions in 1.2.5
  1-js/02-first-steps/05-types/1-string-quotes/solution.md
  1-js/02-first-steps/05-types/1-string-quotes/task.md
  1-js/02-first-steps/05-types/article.md
Labels: needs +1

#107 Fix possible typos, inaccuracies, omissions in 1.2.7
  1-js/02-first-steps/07-type-conversions/article.md
Labels: needs +1

#106 Fix possible typos, inaccuracies, omissions in 1.2.6
  1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/solution.md
  1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/task.md
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
Labels: needs +1

#78 Translate loops
  1-js/02-first-steps/13-while-for/1-loop-last-value/task.md
  1-js/02-first-steps/13-while-for/article.md
Labels: in progress, needs +1

#109 Fix possible typos, inaccuracies, omissions in 1.2.8
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/solution.md
  1-js/02-first-steps/08-operators/4-fix-prompt/solution.md
  1-js/02-first-steps/08-operators/4-fix-prompt/task.md
  1-js/02-first-steps/08-operators/article.md
Labels: needs +1
