Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2020-03, with the labels that each got.

#61 Translate for "Ninja Code" section
  1-js/03-code-quality/04-ninja-code/article.md
Labels: review needed

#62 Translation for js-dataTypes-number
  1-js/05-data-types/02-number/1-sum-interface/solution.md
  1-js/05-data-types/02-number/1-sum-interface/task.md
  1-js/05-data-types/02-number/2-why-rounded-down/solution.md
  1-js/05-data-types/02-number/2-why-rounded-down/task.md
  1-js/05-data-types/02-number/3-repeat-until-number/_js.view/solution.js
  1-js/05-data-types/02-number/3-repeat-until-number/solution.md
  1-js/05-data-types/02-number/3-repeat-until-number/task.md
  1-js/05-data-types/02-number/4-endless-loop-error/solution.md
  1-js/05-data-types/02-number/4-endless-loop-error/task.md
  1-js/05-data-types/02-number/8-random-min-max/solution.md
  1-js/05-data-types/02-number/8-random-min-max/task.md
  1-js/05-data-types/02-number/9-random-int-min-max/solution.md
  1-js/05-data-types/02-number/9-random-int-min-max/task.md
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#63 Translation for "Automated testing with Mocha" section
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/solution.md
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/task.md
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/03-code-quality/05-testing-mocha/beforeafter.view/index.html
  1-js/03-code-quality/05-testing-mocha/beforeafter.view/test.js
  1-js/03-code-quality/05-testing-mocha/index.html
  1-js/03-code-quality/05-testing-mocha/pow-1.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-1.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-2.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-2.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-3.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-3.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-4.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-4.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-full.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-full.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-min.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-min.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-nan.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-nan.view/test.js
Labels: needs +1

#75 Translate "Polyfills" section
  1-js/03-code-quality/06-polyfills/article.md
Labels: needs +1

#77 Translate:12-while-for
  1-js/02-first-steps/12-while-for/article.md
Labels: changes requested
