Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2021-07, with the labels that each got.

#142 Переклад Object copy
  1-js/04-object-basics/02-object-copy/article.md
  1-js/04-object-basics/02-object-copy/variable-copy-value.svg
Labels: needs +1

#127 Functions
  1-js/02-first-steps/15-function-basics/article.md
Labels: changes requested

#146 Optional chaining ?.
  1-js/04-object-basics/07-optional-chaining/article.md
Labels: review needed

#148 Map and Set translation
  1-js/05-data-types/07-map-set/01-array-unique-map/_js.view/test.js
  1-js/05-data-types/07-map-set/01-array-unique-map/task.md
  1-js/05-data-types/07-map-set/02-filter-anagrams/_js.view/test.js
  1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
  1-js/05-data-types/07-map-set/02-filter-anagrams/task.md
  1-js/05-data-types/07-map-set/03-iterable-keys/solution.md
  1-js/05-data-types/07-map-set/03-iterable-keys/task.md
  1-js/05-data-types/07-map-set/article.md
Labels: needs +1

#149 Symbol type
  1-js/04-object-basics/08-symbol/article.md
Labels: needs +1

#151 Object methods, "this"
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/task.md
  1-js/04-object-basics/04-object-methods/7-calculator/task.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/solution.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/task.md
  1-js/04-object-basics/04-object-methods/article.md
Labels: needs +1

#154 Object to primitive conversion
  1-js/04-object-basics/09-object-toprimitive/article.md
Labels: needs +1

#155 Object.keys, values, entries
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/solution.md
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/task.md
  1-js/05-data-types/09-keys-values-entries/02-count-properties/task.md
  1-js/05-data-types/09-keys-values-entries/article.md
Labels: review needed
