Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2021-11, with the labels that each got.

#212 Static properties and methods
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/solution.md
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/task.md
  1-js/09-classes/03-static-properties-methods/animal-rabbit-static.svg
  1-js/09-classes/03-static-properties-methods/article.md
Labels: needs +1

#214 Extending built-in classes
  1-js/09-classes/05-extend-natives/article.md
Labels: changes requested

#215 Prototype methods, objects without proto
  1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/solution.md
  1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/task.md
  1-js/08-prototypes/04-prototype-methods/3-compare-calls/solution.md
  1-js/08-prototypes/04-prototype-methods/3-compare-calls/task.md
  1-js/08-prototypes/04-prototype-methods/article.md
Labels: needs +1

#217 Promise API
  1-js/11-async/05-promise-api/article.md
Labels: needs +1

#218 Class inheritance
  1-js/09-classes/02-class-inheritance/1-class-constructor-error/solution.md
  1-js/09-classes/02-class-inheritance/1-class-constructor-error/task.md
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/task.md
  1-js/09-classes/02-class-inheritance/article.md
  1-js/09-classes/02-class-inheritance/rabbit-animal-independent-animal.svg
  1-js/09-classes/02-class-inheritance/rabbit-animal-independent-rabbit.svg
  1-js/09-classes/02-class-inheritance/super-homeobject-wrong.svg
Labels: needs +1

#219 Variable scope, closure
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/solution.md
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
  1-js/06-advanced-functions/03-closure/10-make-army/_js.view/solution.js
  1-js/06-advanced-functions/03-closure/10-make-army/_js.view/source.js
  1-js/06-advanced-functions/03-closure/10-make-army/_js.view/test.js
  1-js/06-advanced-functions/03-closure/10-make-army/solution.md
  1-js/06-advanced-functions/03-closure/10-make-army/task.md
  1-js/06-advanced-functions/03-closure/2-closure-variable-access/solution.md
  1-js/06-advanced-functions/03-closure/2-closure-variable-access/task.md
  1-js/06-advanced-functions/03-closure/3-counter-independent/solution.md
  1-js/06-advanced-functions/03-closure/3-counter-independent/task.md
  1-js/06-advanced-functions/03-closure/4-counter-object-independent/solution.md
  1-js/06-advanced-functions/03-closure/4-counter-object-independent/task.md
  1-js/06-advanced-functions/03-closure/5-function-in-if/solution.md
  1-js/06-advanced-functions/03-closure/5-function-in-if/task.md
  1-js/06-advanced-functions/03-closure/6-closure-sum/solution.md
  1-js/06-advanced-functions/03-closure/6-closure-sum/task.md
  1-js/06-advanced-functions/03-closure/7-let-scope/solution.md
  1-js/06-advanced-functions/03-closure/7-let-scope/task.md
  1-js/06-advanced-functions/03-closure/8-filter-through-function/_js.view/source.js
  1-js/06-advanced-functions/03-closure/8-filter-through-function/_js.view/test.js
  1-js/06-advanced-functions/03-closure/8-filter-through-function/solution.md
  1-js/06-advanced-functions/03-closure/8-filter-through-function/task.md
  1-js/06-advanced-functions/03-closure/9-sort-by-field/_js.view/source.js
  1-js/06-advanced-functions/03-closure/9-sort-by-field/_js.view/test.js
  1-js/06-advanced-functions/03-closure/9-sort-by-field/task.md
  1-js/06-advanced-functions/03-closure/article.md
  1-js/06-advanced-functions/03-closure/closure-makecounter-nested-call-2.svg
  1-js/06-advanced-functions/03-closure/closure-makecounter.svg
  1-js/06-advanced-functions/03-closure/closure-variable-phrase.svg
  1-js/06-advanced-functions/03-closure/lexical-environment-simple.svg
Labels: needs +1

#220 Nullish coalescing operator '??'
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
Labels: needs +1

#221 Async/await
  1-js/11-async/08-async-await/01-rewrite-async/solution.md
  1-js/11-async/08-async-await/01-rewrite-async/task.md
  1-js/11-async/08-async-await/02-rewrite-async-2/solution.md
  1-js/11-async/08-async-await/02-rewrite-async-2/task.md
  1-js/11-async/08-async-await/03-async-from-regular/solution.md
  1-js/11-async/08-async-await/03-async-from-regular/task.md
  1-js/11-async/08-async-await/article.md
  1-js/11-async/index.md
Labels: review needed, needs +1

#222 Destructuring assignment
  1-js/05-data-types/10-destructuring-assignment/1-destruct-user/solution.md
  1-js/05-data-types/10-destructuring-assignment/1-destruct-user/task.md
  1-js/05-data-types/10-destructuring-assignment/6-max-salary/task.md
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: needs +1

#223 Microtasks
  1-js/11-async/07-microtask-queue/article.md
  1-js/11-async/07-microtask-queue/promiseQueue.svg
Labels: changes requested
