Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2022-10, with the labels that each got.

#383 Character Classes
  9-regular-expressions/02-regexp-character-classes/article.md
Labels: needs +1

#374 Unicode: flag "u" and class \p{...}
  9-regular-expressions/03-regexp-unicode/article.md
Labels: needs +1, in progress

#376 Anchors: string start ^ and end $
  9-regular-expressions/04-regexp-anchors/1-start-end/solution.md
  9-regular-expressions/04-regexp-anchors/1-start-end/task.md
  9-regular-expressions/04-regexp-anchors/article.md
Labels: changes requested, in progress

#393 Fix: orthography / translation (minor corrections)
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: needs +1

#391 Update family.svg
  1-js/04-object-basics/03-garbage-collection/family.svg
Labels: review needed

#390 Update memory-user-john.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john.svg
Labels: needs +1

#392 fix: Suggested better meaning
  1-js/04-object-basics/06-constructor-new/article.md
  1-js/07-object-properties/02-property-accessors/article.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: needs +1

#385 Updated solution.md
  1-js/05-data-types/01-primitives-methods/1-string-new-property/solution.md
Labels: needs +1

#386 Update article.md
  1-js/05-data-types/01-primitives-methods/article.md
Labels: needs +1

#387 Update article.md
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#389 Update article.md
  1-js/02-first-steps/13-while-for/article.md
Labels: needs +1

#397 Update article.md
  1-js/02-first-steps/03-strict-mode/article.md
Labels: needs +1

#381 Shadow DOM slots, composition
  8-web-components/5-slots-composition/article.md
  8-web-components/5-slots-composition/menu.view/index.html
Labels: needs +1

#382 Fetch: Cross-Origin Requests
  5-network/05-fetch-crossorigin/1-do-we-need-origin/solution.md
  5-network/05-fetch-crossorigin/1-do-we-need-origin/task.md
  5-network/05-fetch-crossorigin/article.md
  5-network/05-fetch-crossorigin/cors-gmail-messages.svg
  5-network/05-fetch-crossorigin/xhr-another-domain.svg
  5-network/05-fetch-crossorigin/xhr-preflight.svg
Labels: needs +1

#388 Alternation (OR) |
  9-regular-expressions/13-regexp-alternation/01-find-programming-language/solution.md
  9-regular-expressions/13-regexp-alternation/01-find-programming-language/task.md
  9-regular-expressions/13-regexp-alternation/02-find-matching-bbtags/solution.md
  9-regular-expressions/13-regexp-alternation/02-find-matching-bbtags/task.md
  9-regular-expressions/13-regexp-alternation/03-match-quoted-string/solution.md
  9-regular-expressions/13-regexp-alternation/03-match-quoted-string/task.md
  9-regular-expressions/13-regexp-alternation/04-match-exact-tag/solution.md
  9-regular-expressions/13-regexp-alternation/04-match-exact-tag/task.md
  9-regular-expressions/13-regexp-alternation/article.md
Labels: needs +1
