Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2022-06, with the labels that each got.

#336 Astropsy999 indexedDB
  6-data-storage/03-indexeddb/article.md
  6-data-storage/03-indexeddb/books.view/index.html
Labels: needs +1

#335 Prototype translations fix
  1-js/08-prototypes/02-function-prototype/article.md
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: needs +1

#337 From the orbital height
  8-web-components/1-webcomponents-intro/article.md
  8-web-components/index.md
Labels: needs +1

#338 Update article.md
  1-js/07-object-properties/02-property-accessors/article.md
Labels: needs +1

#340 An Introduction to JavaScript
  1-js/01-getting-started/1-intro/article.md
Labels: needs +1

#345 Remove repeated word
  2-ui/1-document/02-dom-nodes/article.md
Labels: needs +1

#350 Introduction fix
  1-js/01-getting-started/1-intro/article.md
  1-js/02-first-steps/15-function-basics/article.md
Labels: needs +1

#349 Fixed typo in word змінна
  1-js/02-first-steps/15-function-basics/article.md
Labels: review needed

#351 Template element
  8-web-components/4-template-element/article.md
Labels: review needed

#344 Bezier curve
  7-animation/1-bezier-curve/article.md
Labels: review needed, in progress
