Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2022-03, with the labels that each got.

#321 Update article.md
  1-js/09-classes/01-class/article.md
Labels: changes requested

#314 Focus/blur. Translated article and tasks
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/solution.view/index.html
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/solution.view/my.css
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/source.view/index.html
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/source.view/my.css
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/task.md
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.md
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.view/bagua.css
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.view/index.html
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.view/my.css
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.view/script.js
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/source.view/bagua.css
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/source.view/index.html
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/source.view/my.css
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/source.view/script.js
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/task.md
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.md
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.view/index.html
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/source.view/index.html
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/task.md
  2-ui/4-forms-controls/2-focus-blur/article.md
Labels: review needed

#322 Drag'n'Drop with mouse events
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/source.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.md
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/soccer.css
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/soccer.js
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/soccer.css
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/soccer.js
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
  2-ui/3-event-details/4-mouse-drag-and-drop/article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/ball.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/ball2.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/ball3.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/ball4.view/index.html
Labels: needs +1
