Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2022-01, with the labels that each got.

#246 Searching: getElement*, querySelector*
  2-ui/1-document/04-searching-elements-dom/1-find-elements/solution.md
  2-ui/1-document/04-searching-elements-dom/1-find-elements/task.md
  2-ui/1-document/04-searching-elements-dom/article.md
Labels: needs +1

#252 Private and protected properties and methods
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: needs +1

#248 ArrayBuffer, binary arrays
  4-binary/01-arraybuffer-binary-arrays/01-concat/_js.view/solution.js
  4-binary/01-arraybuffer-binary-arrays/01-concat/_js.view/source.js
  4-binary/01-arraybuffer-binary-arrays/article.md
Labels: needs +1

#249 Dom nodes
  2-ui/1-document/02-dom-nodes/article.md
  2-ui/1-document/02-dom-nodes/elk.html
Labels: needs +1

#250 Native Prototypes
  1-js/08-prototypes/03-native-prototypes/1-defer-to-prototype/solution.md
  1-js/08-prototypes/03-native-prototypes/1-defer-to-prototype/task.md
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/solution.md
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/task.md
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: needs +1

#251 Custom errors, extending Error
  1-js/10-error-handling/2-custom-errors/1-format-error/task.md
  1-js/10-error-handling/2-custom-errors/article.md
Labels: needs +1

#253 Introduction: callbacks
  1-js/11-async/01-callbacks/article.md
Labels: needs +1

#254 Reference Type
  1-js/99-js-misc/04-reference-type/2-check-syntax/solution.md
  1-js/99-js-misc/04-reference-type/2-check-syntax/task.md
  1-js/99-js-misc/04-reference-type/3-why-this/solution.md
  1-js/99-js-misc/04-reference-type/3-why-this/task.md
  1-js/99-js-misc/04-reference-type/article.md
Labels: needs +1

#255 update article.md
  1-js/01-getting-started/1-intro/article.md
Labels: review needed

#257 Translations/currying
  1-js/99-js-misc/03-currying-partials/article.md
Labels: needs +1

#256 TextDecoder and TextEncoder
  4-binary/02-text-decoder/article.md
Labels: needs +1

#259 Promises chaining
  1-js/11-async/03-promise-chaining/01-then-vs-catch/solution.md
  1-js/11-async/03-promise-chaining/01-then-vs-catch/task.md
  1-js/11-async/03-promise-chaining/article.md
  1-js/11-async/03-promise-chaining/promise-handler-variants.svg
  images.yml
Labels: needs +1

#260 Basic DOM Node Properties
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/solution.md
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/task.md
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.md
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.view/index.html
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/source.view/index.html
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/task.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/solution.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/task.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/solution.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/task.md
  2-ui/1-document/05-basic-dom-node-properties/article.md
Labels: needs +1

#262 Event delegation
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/solution.view/index.html
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/source.view/index.html
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/solution.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/solution.view/index.html
  2-ui/2-events/03-event-delegation/2-sliding-tree/source.view/index.html
  2-ui/2-events/03-event-delegation/2-sliding-tree/task.md
  2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html
  2-ui/2-events/03-event-delegation/3-sortable-table/source.view/index.html
  2-ui/2-events/03-event-delegation/3-sortable-table/task.md
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/solution.view/index.html
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/source.view/index.html
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md
  2-ui/2-events/03-event-delegation/article.md
  2-ui/2-events/03-event-delegation/bagua.view/index.html
Labels: needs +1

#265 Attributes and properties
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/task.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.view/index.html
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/source.view/index.html
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/task.md
  2-ui/1-document/06-dom-attributes-and-properties/article.md
Labels: needs +1

#268 Dispatching custom events
  2-ui/2-events/05-dispatch-events/article.md
Labels: needs +1

#269 Переклад заголовків другої частини підручника
  2-ui/1-document/index.md
  2-ui/2-events/index.md
  2-ui/3-event-details/index.md
  2-ui/4-forms-controls/index.md
  2-ui/5-loading/index.md
  2-ui/99-ui-misc/index.md
  2-ui/index.md
Labels: needs +1

#275 devtools fix
  1-js/01-getting-started/4-devtools/article.md
Labels: needs +1

#271 fix itnro
  1-js/01-getting-started/1-intro/article.md
Labels: needs +1

#276 fix manual specifications
  1-js/01-getting-started/2-manuals-specifications/article.md
Labels: needs +1

#278 first steps little fix
  1-js/02-first-steps/index.md
Labels: needs +1

#284 types fix
  1-js/02-first-steps/05-types/article.md
Labels: needs +1

#283 variables fix
  1-js/02-first-steps/04-variables/article.md
Labels: needs +1

#282 structure fix
  1-js/02-first-steps/02-structure/article.md
Labels: needs +1

#280 hello world - fix button name
  1-js/02-first-steps/01-hello-world/article.md
Labels: needs +1

#270 Blob
  4-binary/03-blob/article.md
Labels: needs +1

#273 Scripts: async, defer
  2-ui/5-loading/02-script-async-defer/article.md
  2-ui/5-loading/02-script-async-defer/long.js
  2-ui/5-loading/02-script-async-defer/small.js
Labels: needs +1

#274 Mouse events
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/solution.view/index.html
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/source.view/index.html
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/task.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
Labels: needs +1

#289 Fix: Scripts: async, defer
  2-ui/5-loading/02-script-async-defer/article.md
Labels: needs +1

#286 fix 06-alert-prompt-confirm
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
Labels: needs +1

#287 07-type-conversions fix
  1-js/02-first-steps/07-type-conversions/article.md
Labels: review needed

#291 Pointer events
  2-ui/3-event-details/6-pointer-events/article.md
  2-ui/3-event-details/6-pointer-events/ball-2.view/index.html
  2-ui/3-event-details/6-pointer-events/ball.view/index.html
  2-ui/3-event-details/6-pointer-events/multitouch.view/index.html
  2-ui/3-event-details/6-pointer-events/slider.view/index.html
Labels: review needed

#294 Fetch: Download progress
  5-network/03-fetch-progress/article.md
  5-network/03-fetch-progress/progress.view/index.html
Labels: review needed

#300 4-fix-prompt
  1-js/02-first-steps/08-operators/4-fix-prompt/task.md
Labels: needs +1

#295 Scrolling
  2-ui/3-event-details/8-onscroll/1-endless-page/solution.md
  2-ui/3-event-details/8-onscroll/1-endless-page/solution.view/index.html
  2-ui/3-event-details/8-onscroll/1-endless-page/source.view/index.html
  2-ui/3-event-details/8-onscroll/1-endless-page/task.md
  2-ui/3-event-details/8-onscroll/2-updown-button/solution.view/index.html
  2-ui/3-event-details/8-onscroll/2-updown-button/source.view/index.html
  2-ui/3-event-details/8-onscroll/2-updown-button/task.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/solution.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/solution.view/index.html
  2-ui/3-event-details/8-onscroll/3-load-visible-img/source.view/index.html
  2-ui/3-event-details/8-onscroll/3-load-visible-img/task.md
  2-ui/3-event-details/8-onscroll/article.md
Labels: needs +1

#296 Styles and classes
  2-ui/1-document/08-styles-and-classes/2-create-notification/solution.view/index.html
  2-ui/1-document/08-styles-and-classes/2-create-notification/source.view/index.html
  2-ui/1-document/08-styles-and-classes/2-create-notification/task.md
  2-ui/1-document/08-styles-and-classes/article.md
Labels: changes requested

#293 Keyboard: keydown and keyup
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/solution.md
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/solution.view/index.html
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/task.md
  2-ui/3-event-details/7-keyboard-events/article.md
  2-ui/3-event-details/7-keyboard-events/keyboard-dump.view/index.html
Labels: needs +1

#301 File and FileReader
  4-binary/04-file/article.md
Labels: review needed

#298 Forms: event and method submit
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.md
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.view/index.html
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/source.view/index.html
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/task.md
  2-ui/4-forms-controls/4-forms-submit/article.md
Labels: needs +1

#297 Events: change, input, cut, copy, paste
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/solution.view/index.html
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/source.view/index.html
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/task.md
  2-ui/4-forms-controls/3-events-change-input/article.md
Labels: needs +1

#288 08-operators fix
  1-js/02-first-steps/08-operators/article.md
Labels: changes requested
