Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2022-02, with the labels that each got.

#308 Form properties and methods
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
  2-ui/4-forms-controls/1-form-elements/article.md
Labels: needs +1

#309 Form properties and methods
  2-ui/4-forms-controls/1-form-elements/article.md
Labels: review needed

#306 Fetch: Abort
  5-network/04-fetch-abort/article.md
Labels: needs +1

#304 Resource loading: onload and onerror
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/solution.md
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/solution.view/index.html
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/source.view/index.html
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/task.md
  2-ui/5-loading/03-onload-onerror/article.md
Labels: needs +1

#310 XMLHttpRequest
  5-network/08-xmlhttprequest/article.md
  5-network/08-xmlhttprequest/hello.txt
Labels: needs +1

#307 Popups and window methods
  3-frames-and-windows/01-popup-windows/article.md
Labels: needs +1

#305 Coordinates
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.md
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.view/index.html
  2-ui/1-document/11-coordinates/1-find-point-coordinates/source.view/index.html
  2-ui/1-document/11-coordinates/1-find-point-coordinates/task.md
  2-ui/1-document/11-coordinates/2-position-at/solution.md
  2-ui/1-document/11-coordinates/2-position-at/solution.view/index.html
  2-ui/1-document/11-coordinates/2-position-at/source.view/index.html
  2-ui/1-document/11-coordinates/2-position-at/task.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/solution.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/solution.view/index.html
  2-ui/1-document/11-coordinates/3-position-at-absolute/task.md
  2-ui/1-document/11-coordinates/4-position-inside-absolute/solution.view/index.html
  2-ui/1-document/11-coordinates/4-position-inside-absolute/task.md
  2-ui/1-document/11-coordinates/article.md
Labels: needs +1

#303 Page: DOMContentLoaded, load, beforeunload, unload
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
  2-ui/5-loading/01-onload-ondomcontentloaded/readystate.view/iframe.html
  2-ui/5-loading/01-onload-ondomcontentloaded/readystate.view/index.html
  2-ui/5-loading/01-onload-ondomcontentloaded/window-onbeforeunload.view/index.html
Labels: needs +1

#312 Resumable file upload
  5-network/09-resume-upload/article.md
  5-network/09-resume-upload/upload-resume.view/index.html
  5-network/09-resume-upload/upload-resume.view/server.js
  5-network/09-resume-upload/upload-resume.view/uploader.js
Labels: needs +1

#299 Modifying the document
  1-js/01-getting-started/4-devtools/article.md
  1-js/02-first-steps/02-structure/article.md
  1-js/02-first-steps/04-variables/article.md
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
  1-js/02-first-steps/07-type-conversions/article.md
  1-js/11-async/03-promise-chaining/article.md
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.view/index.html
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/source.view/index.html
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/solution.md
  2-ui/1-document/05-basic-dom-node-properties/article.md
  2-ui/1-document/06-dom-attributes-and-properties/article.md
  2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/solution.md
  2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/task.md
  2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
  2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.view/index.html
  2-ui/1-document/07-modifying-document/10-clock-setinterval/source.view/index.html
  2-ui/1-document/07-modifying-document/10-clock-setinterval/task.md
  2-ui/1-document/07-modifying-document/11-append-to-list/solution.md
  2-ui/1-document/07-modifying-document/11-append-to-list/task.md
  2-ui/1-document/07-modifying-document/12-sort-table/solution.md
  2-ui/1-document/07-modifying-document/12-sort-table/solution.view/index.html
  2-ui/1-document/07-modifying-document/12-sort-table/source.view/index.html
  2-ui/1-document/07-modifying-document/12-sort-table/task.md
  2-ui/1-document/07-modifying-document/4-clear-elem/solution.md
  2-ui/1-document/07-modifying-document/4-clear-elem/task.md
  2-ui/1-document/07-modifying-document/5-why-aaa/solution.md
  2-ui/1-document/07-modifying-document/5-why-aaa/task.md
  2-ui/1-document/07-modifying-document/6-create-list/solution.md
  2-ui/1-document/07-modifying-document/6-create-list/solution.view/index.html
  2-ui/1-document/07-modifying-document/6-create-list/task.md
  2-ui/1-document/07-modifying-document/7-create-object-tree/build-tree-dom.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/innerhtml.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/solution.md
  2-ui/1-document/07-modifying-document/7-create-object-tree/source.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/task.md
  2-ui/1-document/07-modifying-document/8-tree-count/solution.md
  2-ui/1-document/07-modifying-document/8-tree-count/solution.view/index.html
  2-ui/1-document/07-modifying-document/8-tree-count/source.view/index.html
  2-ui/1-document/07-modifying-document/8-tree-count/task.md
  2-ui/1-document/07-modifying-document/9-calendar-table/solution.md
  2-ui/1-document/07-modifying-document/9-calendar-table/solution.view/index.html
  2-ui/1-document/07-modifying-document/9-calendar-table/source.view/index.html
  2-ui/1-document/07-modifying-document/9-calendar-table/task.md
  2-ui/1-document/07-modifying-document/article.md
  2-ui/1-document/10-size-and-scroll-window/article.md
  2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html
  2-ui/2-events/03-event-delegation/3-sortable-table/source.view/index.html
  2-ui/2-events/03-event-delegation/3-sortable-table/task.md
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md
  2-ui/2-events/03-event-delegation/article.md
  2-ui/2-events/04-default-browser-action/article.md
  2-ui/2-events/05-dispatch-events/article.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
  2-ui/5-loading/02-script-async-defer/article.md
  4-binary/03-blob/article.md
  images.yml
Labels: partially reviewed, needs +1

#292 Feature/introduction browser events
  2-ui/2-events/01-introduction-browser-events/01-hide-other/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/01-hide-other/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/01-hide-other/task.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/solution.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/solution.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/task.md
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/solution.md
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/task.md
  2-ui/2-events/01-introduction-browser-events/06-hide-message/solution.md
  2-ui/2-events/01-introduction-browser-events/06-hide-message/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/06-hide-message/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/06-hide-message/task.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/solution.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/07-carousel/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/07-carousel/source.view/style.css
  2-ui/2-events/01-introduction-browser-events/07-carousel/task.md
  2-ui/2-events/01-introduction-browser-events/article.md
Labels: review needed

#318 Update article.md
  1-js/10-error-handling/2-custom-errors/article.md
Labels: review needed

#313 Long polling
  5-network/10-long-polling/article.md
  5-network/10-long-polling/longpoll.view/browser.js
  5-network/10-long-polling/longpoll.view/index.html
  5-network/10-long-polling/longpoll.view/server.js
Labels: review needed

#317 Update article.md
  1-js/05-data-types/04-array/article.md
Labels: review needed, in progress

#319 Update article.md
  1-js/01-getting-started/1-intro/article.md
Labels: needs +1
