Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2022-08, with the labels that each got.

#343 The clickjacking attack
  3-frames-and-windows/06-clickjacking/article.md
  3-frames-and-windows/06-clickjacking/clickjacking-visible.view/facebook.html
  3-frames-and-windows/06-clickjacking/clickjacking-visible.view/index.html
  3-frames-and-windows/06-clickjacking/clickjacking.view/facebook.html
  3-frames-and-windows/06-clickjacking/clickjacking.view/index.html
  3-frames-and-windows/06-clickjacking/protector.view/iframe.html
  3-frames-and-windows/06-clickjacking/top-location.view/iframe.html
  3-frames-and-windows/06-clickjacking/top-location.view/index.html
  5-network/12-server-sent-events/article.md
  5-network/12-server-sent-events/eventsource.view/index.html
  6-data-storage/03-indexeddb/article.md
  7-animation/2-css-animations/4-animate-circle-callback/task.md
  7-animation/2-css-animations/article.md
  7-animation/2-css-animations/boat.view/index.html
  7-animation/2-css-animations/digits-negative-delay.view/index.html
  7-animation/2-css-animations/digits.view/index.html
  7-animation/2-css-animations/step-end.view/index.html
  7-animation/2-css-animations/step.view/index.html
Labels: needs +1, in progress

#372 Mutation observer
  2-ui/99-ui-misc/01-mutation-observer/article.md
Labels: needs +1

#377 minor translation fix
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
Labels: needs +1

#375 fix: translation
  1-js/06-advanced-functions/01-recursion/01-sum-to/task.md
  1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/solution.md
  1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/task.md
  1-js/06-advanced-functions/01-recursion/article.md
Labels: needs +1

#373 fix: code block; add missing translations;
  1-js/05-data-types/06-iterable/article.md
Labels: review needed
