Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2022-11, with the labels that each got.

#411 Update article.md
  1-js/01-getting-started/1-intro/article.md
Labels: changes requested

#402 Update task.md
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/task.md
Labels: needs +1

#404 Update solution.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/solution.md
Labels: needs +1

#405 Update task.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/task.md
Labels: needs +1

#406 Update task.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
Labels: needs +1

#408 Update solution.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
Labels: needs +1

#415 Fixes for translation inaccuracies
  1-js/06-advanced-functions/02-rest-parameters-spread/article.md
Labels: needs +1

#416 Update article.md
  1-js/02-first-steps/13-while-for/article.md
Labels: needs +1

#422 Fix after review: Manuals and specifications, Code editors, Developer console
  1-js/01-getting-started/2-manuals-specifications/article.md
  1-js/01-getting-started/3-code-editors/article.md
  1-js/01-getting-started/4-devtools/article.md
  1-js/99-js-misc/04-reference-type/2-check-syntax/solution.md
Labels: review needed
