Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2023-08, with the labels that each got.

#510 Shadow DOM
  8-web-components/3-shadow-dom/article.md
Labels: changes requested, in progress

#527 Correction of translation errors
  1-js/05-data-types/12-json/article.md
Labels: needs +1

#529 fix(2-1.4): Review `Searching: getElement*, querySelector*` article
  2-ui/1-document/04-searching-elements-dom/article.md
Labels: needs +1

#530 fix,traslate(2-1.5): Fix and traslate `Node properties: type, tag and contents` article
  2-ui/1-document/05-basic-dom-node-properties/article.md
  2-ui/1-document/05-basic-dom-node-properties/dom-class-hierarchy.svg
Labels: needs +1

#538 Update index.md
  9-regular-expressions/index.md
Labels: needs +1

#536 fix(2-1.10): Review `Window sizes and scrolling` article
  2-ui/1-document/10-size-and-scroll-window/article.md
Labels: needs +1

#535 fix(2-1.9): Review `Size and scroll` article
  2-ui/1-document/09-size-and-scroll/article.md
  2-ui/1-document/09-size-and-scroll/cssWidthScroll.view/index.html
  2-ui/1-document/09-size-and-scroll/metric.view/index.html
Labels: needs +1

#533 fix(2-1.8): Review `Styles and classes` article
  2-ui/1-document/08-styles-and-classes/article.md
Labels: needs +1

#509 Unicode, String internals
  1-js/99-js-misc/06-unicode/article.md
Labels: needs +1, in progress

#543 fix #282 fixing litells mistakes
  1-js/01-getting-started/4-devtools/article.md
  1-js/02-first-steps/01-hello-world/1-hello-alert/task.md
  1-js/02-first-steps/05-types/article.md
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
Labels: needs +1

#450 Greedy and lazy quantifiers
  9-regular-expressions/10-regexp-greedy-and-lazy/1-lazy-greedy/solution.md
  9-regular-expressions/10-regexp-greedy-and-lazy/1-lazy-greedy/task.md
  9-regular-expressions/10-regexp-greedy-and-lazy/3-find-html-comments/solution.md
  9-regular-expressions/10-regexp-greedy-and-lazy/3-find-html-comments/task.md
  9-regular-expressions/10-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/solution.md
  9-regular-expressions/10-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/task.md
  9-regular-expressions/10-regexp-greedy-and-lazy/article.md
Labels: needs +1
