Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2024-03, with the labels that each got.

#576 Переклад розділу: WeakRef и FinalizationRegistry
  1-js/99-js-misc/07-weakref-finalizationregistry/article.md
  1-js/99-js-misc/07-weakref-finalizationregistry/weakref-dom.view/index.html
  1-js/99-js-misc/07-weakref-finalizationregistry/weakref-dom.view/index.js
  1-js/99-js-misc/07-weakref-finalizationregistry/weakref-finalizationregistry-03.svg
  1-js/99-js-misc/07-weakref-finalizationregistry/weakref-finalizationregistry-04.svg
  1-js/99-js-misc/07-weakref-finalizationregistry/weakref-finalizationregistry-05.svg
Labels: needs +1, in progress

#616 Fix info links
  1-js/04-object-basics/04-object-methods/article.md
  5-network/01-fetch/article.md
Labels: needs +1

#617 Translate/fix all words with "ы"
  5-network/03-fetch-progress/progress.view/long.txt
  5-network/12-server-sent-events/article.md
Labels: needs +1

#618 Update article.md
  8-web-components/3-shadow-dom/article.md
Labels: needs +1

#620 3-mousemove-mouseover-mouseout-mouseenter-mouseleave
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/solution.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/source.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.view/hoverIntent.js
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/source.view/hoverIntent.js
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseenter-mouseleave-delegation-2.view/script.js
Labels: review needed
