Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2024-08, with the labels that each got.

#631 minor fixes
  1-js/04-object-basics/09-object-toprimitive/article.md
Labels: review needed

#630 Update article.md
  1-js/02-first-steps/13-while-for/article.md
Labels: needs +1

#629 Update article.md
  1-js/03-code-quality/05-testing-mocha/article.md
Labels: changes requested, needs +1

#550 Update article.md & all SVGs
  9-regular-expressions/10-regexp-greedy-and-lazy/article.md
  9-regular-expressions/10-regexp-greedy-and-lazy/witch_greedy1.svg
  9-regular-expressions/10-regexp-greedy-and-lazy/witch_greedy2.svg
  9-regular-expressions/10-regexp-greedy-and-lazy/witch_greedy3.svg
  9-regular-expressions/10-regexp-greedy-and-lazy/witch_greedy4.svg
  9-regular-expressions/10-regexp-greedy-and-lazy/witch_greedy5.svg
  9-regular-expressions/10-regexp-greedy-and-lazy/witch_greedy6.svg
  9-regular-expressions/10-regexp-greedy-and-lazy/witch_lazy3.svg
  9-regular-expressions/10-regexp-greedy-and-lazy/witch_lazy4.svg
  9-regular-expressions/10-regexp-greedy-and-lazy/witch_lazy5.svg
  9-regular-expressions/10-regexp-greedy-and-lazy/witch_lazy6.svg
Labels: needs +1

#633 Update article.md
  1-js/99-js-misc/05-bigint/article.md
Labels: review needed

#632 Update article.md
  1-js/99-js-misc/05-bigint/article.md
Labels: needs +1
