Repository javascript-tutorial/uk.javascript.info, pull requests merged in 2025-01, with the labels that each got.

#671 Fixing typos in Class Inheritance article
  1-js/09-classes/02-class-inheritance/article.md
Labels: needs +1

#673 Fixing typos in Try-catch article
  1-js/10-error-handling/1-try-catch/article.md
Labels: needs +1

#658 Improved the regular expression to work with Cyrillic and any other l…
  9-regular-expressions/17-regexp-methods/article.md
Labels: needs +1

#675 Eval-calculator translation 2
  1-js/99-js-misc/02-eval/1-eval-calculator/task.md
Labels: needs +1

#674 Eval-calculator translation 1
  1-js/99-js-misc/02-eval/1-eval-calculator/solution.md
Labels: review needed

#676 Fixing typos in Reference Type article
  1-js/99-js-misc/04-reference-type/article.md
Labels: needs +1

#621 Вичитка розділу "Регулярні вирази"
  9-regular-expressions/01-regexp-introduction/article.md
  9-regular-expressions/02-regexp-character-classes/article.md
  9-regular-expressions/03-regexp-unicode/article.md
  9-regular-expressions/04-regexp-anchors/1-start-end/solution.md
  9-regular-expressions/04-regexp-anchors/article.md
  9-regular-expressions/05-regexp-multiline-mode/article.md
  9-regular-expressions/06-regexp-boundary/1-find-time-hh-mm/task.md
  9-regular-expressions/06-regexp-boundary/article.md
  9-regular-expressions/07-regexp-escaping/article.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/task.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
  9-regular-expressions/17-regexp-methods/article.md
Labels: needs +1, WIP

#678 Update article.md
  1-js/06-advanced-functions/04-var/article.md
Labels: needs +1
